language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-def"
addons:
  apt:
    packages:
      - oracle-java8-set-default
env:
  - REDPEN_VERSION=1.9.0
install:
  - pip install coveralls
before_script:
  - unzip ipadic/sysdic.zip
script:
  - coverage run --source=janome setup.py test
after_success:
  - coveralls
  - wget -q https://github.com/redpen-cc/redpen/releases/download/redpen-${REDPEN_VERSION}/redpen-${REDPEN_VERSION}.tar.gz
  - tar xzf redpen-${REDPEN_VERSION}.tar.gz
  - cp docs/redpen/logback.xml redpen-distribution-${REDPEN_VERSION}/conf/logback.xml
  - redpen-distribution-${REDPEN_VERSION}/bin/redpen -c docs/redpen/redpen-conf-ja.xml -f rest docs/ja/index.rst
  - redpen-distribution-${REDPEN_VERSION}/bin/redpen -c docs/redpen/redpen-conf-en.xml -f rest docs/en/index.rst
